### ISSUE TITLE
Successful PinI2C between SAMD21's

### ISSUE THREAD

**Issue by awgrover** [ftjuh/I2Cwrapper#3]
It worked (with small edits):

    controller: adafruit metro express (m0)
    target: adafruit itsybitsy m0
    examples/Pin_control
    edited firmware/firmware_modules.h to include PinI2C_firmware.h
    dPinOut = 13
    dPinIn = 12
    aPinOut = 3
    aPinIn = 14 // A0

Please see
[https://github.com/awgrover/I2Cwrapper/pull/2]()
I did a PR in my repository so it wouldn't clutter up yours (yet). I'll move it to yours if/when you want it.

That PR only has the fixes to enable the samd to work (and only PinI2C). I can implement the accelstepper and servo.

Please also see
[https://github.com/awgrover/I2Cwrapper/pull/2]()
That PR has changes I made to `examples/Pin_control` to enable a step-by-step process of testing. Specifically, I added a "loopback" idea for PinI2C. And, I would do the same if I implement accelstepper and servo.

These changes are more exploratory, and don't have to be accepted with the samd fixes, but it made my life easier.

**Comment by ftjuh** [comment]
See my comments in your repo.

(and the links are not working as they should.)
